services:
  hotelmanagementdb:
    container_name: hotelmanagementdb
    environment:
      - POSTGRES_USER=hotelpostgres
      - POSTGRES_PASSWORD=hotelpostgres
      - POSTGRES_DB=HotelmanagementDb
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - postgres_hotelmanagement:/var/lib/postgresql/data/ 
