services:
  hotelmanagementdb:
    image: postgres

  guestdb:
    image: postgres

  bookingdb:
    image: postgres

  paymentdb:
    image: postgres

  staffdb:
    image: postgres

  notificationdb:
    image: mongo
  
  mongo-express:
    image: mongo-express

  messagebroker:
    image: rabbitmq:management

  authenticationdb:
    image: postgres

  hotelmanagement.api:
    image: ${DOCKER_REGISTRY-}hotelmanagementapi
    build:
      context: .
      dockerfile: Services/HotelManagement/HotelManagement.API/Dockerfile

  guestmanagement.api:
    image: ${DOCKER_REGISTRY-}guestmanagementapi
    build:
      context: .
      dockerfile: Services/GuestManagement/GuestManagement.API/Dockerfile

  bookingmanagement.api:
    image: ${DOCKER_REGISTRY-}bookingmanagementapi
    build:
      context: .
      dockerfile: Services/BookingManagement/BookingManagement.API/Dockerfile

  paymentmanagement.api:
    image: ${DOCKER_REGISTRY-}paymentmanagementapi
    build:
      context: .
      dockerfile: Services/PaymentManagement/PaymentManagement.API/Dockerfile

  staffmanagement.api:
    image: ${DOCKER_REGISTRY-}staffmanagementapi
    build:
      context: .
      dockerfile: Services/StaffManagement/StaffManagement.API/Dockerfile

  notificationmanagement.api:
    image: ${DOCKER_REGISTRY-}notificationmanagementapi
    build:
      context: .
      dockerfile: Services/NotificationManagement/NotificationManagement.API/Dockerfile

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile

volumes:
  postgres_hotelmanagement:    
  postgres_guest:
  postgres_booking:
  postgres_payment:
  postgres_staff:
  mongo_notification:
  postgres_authentication:








