services:
  hotelmanagementdb:
    container_name: hotelmanagementdb
    environment:
      - POSTGRES_USER=hotelpostgres
      - POSTGRES_PASSWORD=hotelpostgres
      - POSTGRES_DB=HotelmanagementDb
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - postgres_hotelmanagement:/var/lib/postgresql/data/ 

  guestdb:
    container_name: guestdb
    environment:
      - POSTGRES_USER=guestpostgres
      - POSTGRES_PASSWORD=guestpostgres
      - POSTGRES_DB=GuestDb
    restart: always
    ports:
        - "5436:5432"
    volumes:
      - postgres_guest:/var/lib/postgresql/data/ 
   
  bookingdb:
    container_name: bookingdb
    environment:
      - POSTGRES_USER=bookingpostgres
      - POSTGRES_PASSWORD=bookingpostgres
      - POSTGRES_DB=BookingDb
    restart: always
    ports:
        - "5437:5432"
    volumes:
      - postgres_booking:/var/lib/postgresql/data/  
    
  financedb:
    container_name: financedb
    environment:
      - POSTGRES_USER=financepostgres
      - POSTGRES_PASSWORD=financepostgres
      - POSTGRES_DB=FinanceDb
    restart: always
    ports:
        - "5438:5432"
    volumes:
      - postgres_finance:/var/lib/postgresql/data/

  staffdb:
    container_name: staffdb
    environment:
      - POSTGRES_USER=staffpostgres
      - POSTGRES_PASSWORD=staffpostgres
      - POSTGRES_DB=StaffDb
    restart: always
    ports:
      - "5439:5432"
    volumes:
      - postgres_staff:/var/lib/postgresql/data/

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    
  authenticationdb:
    container_name: authenticationdb
    environment:
      - POSTGRES_USER=authenticationpostgres
      - POSTGRES_PASSWORD=authenticationpostgres
      - POSTGRES_DB=AuthenticationDb
    restart: always
    ports:
      - "5440:5432"
    volumes:
      - postgres_authentication:/var/lib/postgresql/data/

  hotelmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=hotelmanagementdb;Port=5432;Database=HotelmanagementDb;User Id=hotelpostgres;Password=hotelpostgres;Include Error Detail=true
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - hotelmanagementdb
      - messagebroker
    ports:
      - "6000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  guestmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=guestdb;Port=5432;Database=GuestDb;User Id=guestpostgres;Password=guestpostgres;Include Error Detail=true
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - guestdb
      - messagebroker
    ports:
      - "6001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  bookingmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=bookingdb;Port=5432;Database=BookingDb;User Id=bookingpostgres;Password=bookingpostgres;Include Error Detail=true
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6002:8080"
    depends_on:
      - bookingdb
      - messagebroker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  staffmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=staffdb;Port=5432;Database=StaffDb;User Id=staffpostgres;Password=staffpostgres;Include Error Detail=true
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6004:8080"
      # - "8081"
    depends_on:
      - staffdb
      - messagebroker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=authenticationdb;Port=5432;Database=AuthenticationDb;User Id=authenticationpostgres;Password=authenticationpostgres;Include Error Detail=true
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6006:8080"
    depends_on:
      - authenticationdb
      - messagebroker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
