services:
  hotelmanagementdb:
    container_name: hotelmanagementdb
    environment:
      - POSTGRES_USER=hotelpostgres
      - POSTGRES_PASSWORD=hotelpostgres
      - POSTGRES_DB=HotelmanagementDb
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - postgres_hotelmanagement:/var/lib/postgresql/data/ 

  guestdb:
    container_name: guestdb
    environment:
      - POSTGRES_USER=guestpostgres
      - POSTGRES_PASSWORD=guestpostgres
      - POSTGRES_DB=GuestDb
    restart: always
    ports:
        - "5436:5432"
    volumes:
      - postgres_guest:/var/lib/postgresql/data/ 
   
  bookingdb:
    container_name: bookingdb
    environment:
      - POSTGRES_USER=bookingpostgres
      - POSTGRES_PASSWORD=bookingpostgres
      - POSTGRES_DB=BookingDb
    restart: always
    ports:
        - "5437:5432"
    volumes:
      - postgres_booking:/var/lib/postgresql/data/  
    
  paymentdb:
    container_name: paymentdb
    environment:
      - POSTGRES_USER=paymentpostgres
      - POSTGRES_PASSWORD=paymentpostgres
      - POSTGRES_DB=PaymentDb
    restart: always
    ports:
        - "5438:5432"
    volumes:
      - postgres_payment:/var/lib/postgresql/data/

  staffdb:
    container_name: staffdb
    environment:
      - POSTGRES_USER=staffpostgres
      - POSTGRES_PASSWORD=staffpostgres
      - POSTGRES_DB=StaffDb
    restart: always
    ports:
        - "5439:5432"
    volumes:
      - postgres_staff:/var/lib/postgresql/data/
  hotelmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=hotelmanagementdb;Port=5432;Database=HotelmanagementDb;User Id=hotelpostgres;Password=hotelpostgres;Include Error Detail=true
    depends_on:
      - hotelmanagementdb
    ports:
      - "6000:8080"
      # - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  guestmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=guestdb;Port=5432;Database=GuestDb;User Id=guestpostgres;Password=guestpostgres;Include Error Detail=true
    depends_on:
      - guestdb
    ports:
      - "6001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  bookingmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=bookingdb;Port=5432;Database=BookingDb;User Id=bookingpostgres;Password=bookingpostgres;Include Error Detail=true
    ports:
      - "6002:8080"
    depends_on:
      - bookingdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  paymentmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=paymentdb;Port=5432;Database=PaymentDb;User Id=paymentpostgres;Password=paymentpostgres;Include Error Detail=true
    ports:
      - "6003:8080"
    depends_on:
      - paymentdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
