services:
  hotelmanagementdb:
    image: postgres

  guestdb:
    image: postgres

  bookingdb:
    image: postgres

  financedb:
    image: postgres

  staffdb:
    image: postgres

  messagebroker:
    image: rabbitmq:management

  authenticationdb:
    image: postgres

  hotelmanagement.api:
    image: ${DOCKER_REGISTRY-}hotelmanagementapi
    build:
      context: .
      dockerfile: Services/HotelManagement/HotelManagement.API/Dockerfile

  guestmanagement.api:
    image: ${DOCKER_REGISTRY-}guestmanagementapi
    build:
      context: .
      dockerfile: Services/GuestManagement/GuestManagement.API/Dockerfile

  bookingmanagement.api:
    image: ${DOCKER_REGISTRY-}bookingmanagementapi
    build:
      context: .
      dockerfile: Services/BookingManagement/BookingManagement.API/Dockerfile

  staffmanagement.api:
    image: ${DOCKER_REGISTRY-}staffmanagementapi
    build:
      context: .
      dockerfile: Services/StaffManagement/StaffManagement.API/Dockerfile

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile

  financemanagement.api:
    image: ${DOCKER_REGISTRY-}financemanagementapi
    build:
      context: .
      dockerfile: Services/FinanceManagement/FinanceManagement.API/Dockerfile

volumes:
  postgres_hotelmanagement:    
  postgres_guest:
  postgres_booking:
  postgres_finance:
  postgres_staff:
  postgres_authentication:










